CREATE OR REPLACE FORCE VIEW PELA_STOCK AS
SELECT 
    "REC_N_S","U_VERSION","PROD_N","KN_N","BATCH_N","STOCK_GRU_C","STOCK_CS","AVER_GROSS_W","COMMENT80","CREATOR_DEP","CREATOR_NA","CREATION_D","LAST_CHANGE_D","MUT_D","MUT_DEP","MUT_NA","PROD_TXTS","QUANT_C","QUANT_CONT_STOCK","QUANT_CONT_TRANS","QUANT_STOCK_EFF","QUANT_STOCK_MIN","STATUS1","STOR_PLACE","TARE_W","STOR_POSITION","CONTAINER_TYPE","TRD_MATERIAL_NAME","BATCH_KEY","QUANT_CONT_BLOCKED","QUANT_CONT_UNCHECKED","QUANT_STOCK_BLOCKED","QUANT_STOCK_UNCHECKED"
FROM
PELA_STOCK@PELA;

