CREATE OR REPLACE FORCE VIEW V_SAI_V_TRIAL AS
SELECT 
"TRIAL_NO","STUDY_CODE","CLINICAL_PLAN_NO","CLINICAL_PLAN_CODE","CLINICAL_PLAN_DESC","THERAPY_AREA_CODE","THERAPY_AREA","THERAPY_AREA_ABBREV","STUDY_ACRONYM","STUDY_DESC","STUDY_STATUS","MANAGING_MED_UNIT_CODE","MANAGING_MED_UNIT","STUDY_PHASE_CODE","STUDY_PHASE","DATA_COLLECTION_METHOD","GEO_GLOBAL_LOCAL","LEAD_COUNTRY_CODE","LEAD_COUNTRY_NAME","THIRD_PARTY_STUDY","ACTIVE_SUBSTANCE_CODE","DEVELOPMENT_NAME","TRADE_NAME","PRIMARY_INDICATION_CODE","PRIMARY_INDICATION","SUBJECTS_PLANNED","SUBJECTS_ENROLLED","SUBJECTS_ENTERED_TRT","SUBJECTS_COMPLETED_TRT","PRIMARY_OBJECTIVE_CODE","PRIMARY_OBJECTIVE","CRITICALITY_CODE","CRITICALITY","FINAL_PROT_CRF_PLN_DATE","FINAL_PROT_CRF_ACT_DATE","FPFV_PLN_DATE","FPFV_ACT_DATE","LPFV_PLN_DATE","LPFV_ACT_DATE","LPLV_PLN_DATE","LPLV_ACT_DATE","DBL_PLN_DATE","DBL_ACT_DATE","CSR_PUB_PLN_DATE","CSR_PUB_ACT_DATE","CREATED_DATE","LAST_UPDATED_DATE"    
FROM
SAI_V_TRIAL;

