CREATE OR REPLACE FORCE VIEW FREETEXT_PH_JN AS
SELECT "LABEL_ID",
    "JN_DATETIME",
    "JN_OPERATION",
    "VERSION_NO",
    "PLACEHOLDER_ID",
    "JN_ORACLE_USER"
  FROM FREETEXT_PH_JN@clin.ph.chbs;

