CREATE OR REPLACE FORCE VIEW PELA_MOVE AS
SELECT 
    "CREATION_D","CREATION_T","U_VERSION","STOCK_C","STOCK_GRU_C","YEAR","NUMBER_4","PROD_N","KN_N","BATCH_N","STOCK_CS","STOCK_CS_TO","REC_N_S","ANAL_CERT_TYP","APPL_TYP","BATCH_IMPRINT1","BATCH_IMPRINT2","COMMENT240","CONT_EMPTY","CONT_FROM_N","CONT_TO_N","CREATOR_DEP","CREATOR_NA","MUT_D","EXPIR_D","EXPIR_DS","EXPIR_TXT","MANU_PLACE","MUT_DEP","MUT_NA","QUANT","QUANT_ANAL_CERT","QUANT_RES","QUANT_C","PACK_C","PACK_QUANT","PACK_QUANT_RES","PACK_SIZE","PACK_SIZE_RES","PRICE_ORD","PROD_TXTS","REC_TYP_C","RECORDING_TYP_C","SORT_C","LABEL_TXT","BMF_STATUS","BATCH_TYP","COMP_BATCH_N","AMF_STATUS","CLINICAL_STORAGE","PROV","DECIS_TXT","STOR_INSTR","TRANSP_INSTR","PMF_STATUS","SOURCE_CTRY_N","MOVE_KEY","BATCH_KEY","SIGN_PERSON_KEY","SIGNER","SIGNER_ACCOUNT","SIGN_REASON","QA_CHECK_YN","QA_CHECK_SUCCESS_YN","MOVE_COMMENT","TRD_MATERIAL_NAME","ANAL_N","MOVE_KEY_ASSOC","MOVE_TYPE","STOCK_GRU_C_TO","TRANSP_RECOM","STOR_RECOM"
FROM
PELA_MOVE@PELA;

