create or replace force view runs as
select "LOT_ID","RUN_ID","STATUS","QTY","PRINTER_TYPE","ALL_LEVELS","IS_PRINTED","CREATED_BY","DATE_CREATED","MODIFIED_BY","DATE_MODIFIED","COMPL_SIGN","COMPL_NOTES","REV_COMPL_SIGN","REV_COMPL_NOTES","APPR_SIGN","APPR_NOTES","REV_APPR_SIGN","REV_APPR_NOTES","PRINT_SIGN","PRINT_NOTES","PRINT_QTY","PAGE_CODE","LABEL_ID","VERSION_NO","STUD_ID","LOT_TYPE","IS_SAMPLE_LOT","PROD_CD","COLLATE","LAB_LEVEL","LABEL_SUF_ID","QTY_PER_LABEL","SAMPLE_QTY","KIT_QTY","RANDOM_TYPE","RE_PRINT_OF","PRINTED_BY","DATE_PRINTED" from RUNS@clin;

