CREATE OR REPLACE FORCE VIEW VISIT_PH AS
SELECT "LABEL_ID",
    "VERSION_NO",
    "PLACEHOLDER_ID",
    "DESCRIPTION",
    "CREATED_BY",
    "DATE_CREATED" ,
    "MODIFIED_BY" ,
    "DATE_MODIFIED" ,
    "DEFAULT_VALUE"
  FROM VISIT_PH@clin.lcsys.ch;

