CREATE OR REPLACE TRIGGER "SYS_AUDIT_TRG_CAPAMPWEEK" 
AFTER INSERT OR DELETE OR UPDATE  OF 
COMMENT200,PCN,ENDDATE,DSMUI,NUMBEROFPEOPLE,ASSIGNEDHOURSPERORDE,STATUS,STARTDATE 
ON CAPAMPWEEK 
REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW 
DECLARE    
p_time timestamp;     
p_type char(1); 
BEGIN    
p_time := systimestamp;   
if INSERTING then       
  p_type := 'I';   
elsif DELETING then
  p_type := 'D';   
else       p_type := 'U';   
end if; 

if (:OLD.COMMENT200 is not null and :NEW.COMMENT200 is not null and :OLD.COMMENT200 != :NEW.COMMENT200) or (:OLD.COMMENT200 is not null and :NEW.COMMENT200 is null) or (:OLD.COMMENT200 is null and :NEW.COMMENT200 is not null) then 
   insert into SYS_AUDITS(ID,AUDIT_COLUMNS_ID,USER_ID,OP_TYPE,OP_DATE,INITIAL_VALUE,LAST_VALUE,ID1,ID2, USER_NAME )    
   values (IDSEQ.nextval,11951,nvl(GLOBALVARS.GUSID,1),p_type,p_time,:OLD.COMMENT200,:NEW.COMMENT200,:NEW.ID,NULL,GLOBALVARS.GUSER); 
end if; 
if (:OLD.PCN is not null and :NEW.PCN is not null and :OLD.PCN != :NEW.PCN) or (:OLD.PCN is not null and :NEW.PCN is null) or (:OLD.PCN is null and :NEW.PCN is not null) then
  insert into SYS_AUDITS(ID,AUDIT_COLUMNS_ID,USER_ID,OP_TYPE,OP_DATE,INITIAL_VALUE,LAST_VALUE,ID1,ID2, USER_NAME )    
  values (IDSEQ.nextval,11952,nvl(GLOBALVARS.GUSID,1),p_type,p_time,:OLD.PCN,:NEW.PCN,:NEW.ID,NULL,GLOBALVARS.GUSER); 
end if; 
if (:OLD.ENDDATE is not null and :NEW.ENDDATE is not null and :OLD.ENDDATE != :NEW.ENDDATE) or (:OLD.ENDDATE is not null and :NEW.ENDDATE is null) or (:OLD.ENDDATE is null and :NEW.ENDDATE is not null) then    
   insert into SYS_AUDITS(ID,AUDIT_COLUMNS_ID,USER_ID,OP_TYPE,OP_DATE,INITIAL_VALUE,LAST_VALUE,ID1,ID2, USER_NAME )    
   values (IDSEQ.nextval,11953,nvl(GLOBALVARS.GUSID,1),p_type,p_time,to_char(:OLD.ENDDATE,'dd.mm.yyyy hh24:mi:ss'),to_char(:NEW.ENDDATE,'dd.mm.yyyy hh24:mi:ss'),:NEW.ID,NULL,GLOBALVARS.GUSER); 
end if; 
if (:OLD.DSMUI is not null and :NEW.DSMUI is not null and :OLD.DSMUI != :NEW.DSMUI) or (:OLD.DSMUI is not null and :NEW.DSMUI is null) or (:OLD.DSMUI is null and :NEW.DSMUI is not null) then    
  insert into SYS_AUDITS(ID,AUDIT_COLUMNS_ID,USER_ID,OP_TYPE,OP_DATE,INITIAL_VALUE,LAST_VALUE,ID1,ID2, USER_NAME )    
  values (IDSEQ.nextval,11954,nvl(GLOBALVARS.GUSID,GLOBALVARS.GUSID),p_type,p_time,:OLD.DSMUI,:NEW.DSMUI,:NEW.ID,NULL,GLOBALVARS.GUSER); 
end if; 
if (:OLD.NUMBEROFPEOPLE is not null and :NEW.NUMBEROFPEOPLE is not null and :OLD.NUMBEROFPEOPLE != :NEW.NUMBEROFPEOPLE) or (:OLD.NUMBEROFPEOPLE is not null and :NEW.NUMBEROFPEOPLE is null) or (:OLD.NUMBEROFPEOPLE is null and :NEW.NUMBEROFPEOPLE is not null) then
  insert into SYS_AUDITS(ID,AUDIT_COLUMNS_ID,USER_ID,OP_TYPE,OP_DATE,INITIAL_VALUE,LAST_VALUE,ID1,ID2, USER_NAME )    
  values (IDSEQ.nextval,806654,nvl(GLOBALVARS.GUSID,1),p_type,p_time,:OLD.NUMBEROFPEOPLE,:NEW.NUMBEROFPEOPLE,:NEW.ID,NULL,GLOBALVARS.GUSER); 
end if; 
if (:OLD.ASSIGNEDHOURSPERORDE is not null and :NEW.ASSIGNEDHOURSPERORDE is not null and :OLD.ASSIGNEDHOURSPERORDE != :NEW.ASSIGNEDHOURSPERORDE) or (:OLD.ASSIGNEDHOURSPERORDE is not null and :NEW.ASSIGNEDHOURSPERORDE is null) or (:OLD.ASSIGNEDHOURSPERORDE is null and :NEW.ASSIGNEDHOURSPERORDE is not null) then    
 insert into SYS_AUDITS(ID,AUDIT_COLUMNS_ID,USER_ID,OP_TYPE,OP_DATE,INITIAL_VALUE,LAST_VALUE,ID1,ID2, USER_NAME )    
 values (IDSEQ.nextval,806656,nvl(GLOBALVARS.GUSID,1),p_type,p_time,:OLD.ASSIGNEDHOURSPERORDE,:NEW.ASSIGNEDHOURSPERORDE,:NEW.ID,NULL,GLOBALVARS.GUSER); 
end if; 
if (:OLD.STATUS is not null and :NEW.STATUS is not null and :OLD.STATUS != :NEW.STATUS) or (:OLD.STATUS is not null and :NEW.STATUS is null) or (:OLD.STATUS is null and :NEW.STATUS is not null) then    
  insert into SYS_AUDITS(ID,AUDIT_COLUMNS_ID,USER_ID,OP_TYPE,OP_DATE,INITIAL_VALUE,LAST_VALUE,ID1,ID2, USER_NAME )    
  values (IDSEQ.nextval,806659,nvl(GLOBALVARS.GUSID,1),p_type,p_time,:OLD.STATUS,:NEW.STATUS,:NEW.ID,NULL,GLOBALVARS.GUSER); 
end if; 
if (:OLD.STARTDATE is not null and :NEW.STARTDATE is not null and :OLD.STARTDATE != :NEW.STARTDATE) or (:OLD.STARTDATE is not null and :NEW.STARTDATE is null) or (:OLD.STARTDATE is null and :NEW.STARTDATE is not null) then    
  insert into SYS_AUDITS(ID,AUDIT_COLUMNS_ID,USER_ID,OP_TYPE,OP_DATE,INITIAL_VALUE,LAST_VALUE,ID1,ID2, USER_NAME )    
  values (IDSEQ.nextval,11950,nvl(GLOBALVARS.GUSID,1),p_type,p_time,to_char(:OLD.STARTDATE,'dd.mm.yyyy hh24:mi:ss'),to_char(:NEW.STARTDATE,'dd.mm.yyyy hh24:mi:ss'),:NEW.ID,NULL,GLOBALVARS.GUSER); 
end if; 
end;
/

